spring.application.name=ganaderia

spring.datasource.url=jdbc:postgresql://localhost:5432/ganaderia
spring.datasource.username=postgres
spring.datasource.password=Lab307
spring.datasource.drive-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.mvc.hiddenmethod.filter.enabled=true